spring:
  profiles:
    active: @spring.profiles.active@


# app config
server:
  port: 5000

elena:
  graph:
    inmemory:
      filePath: "graph.json"

    mongodb:
      database: routing
      port: 27017
      host: localhost
      username: user
      password: password
      maxPoolSize: 100